# 导航菜单 — 首页、博客、友链、关于
[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "博客"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "友链"
  pageRef = "/friends"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "/about"
  weight = 40
